### ISSUE TITLE
Record read length dependent on record data 

### ISSUE THREAD

**Issue by mgcth** [traktofon/FortranFiles.jl#3]
Hello,

I'm trying to write a loader in Julia using FortranFiles where the Fortran code has the following line:

READ(10) ICOL, IROW, NW, (WS(K), K=1, NW)

This means that it will use NW, that it read from the record, to determine how much to read in from that record in total. Is there an easy solution for this as is, or would I have to write some extra code to handle this?

**Comment by traktofon** [comment]
Hi,

I'm aware of this problem, but it can't be solved with the current package because NW would not be assigned  before the statement is processed. So I have created a new macro interface which will support this use case. I believe this is working but I haven't included it in my test suite yet so I was reluctant to release it. I'll try to at least get a usable branch up in the next few days.

**Comment by mgcth** [comment]
Sounds great! Right now I solve it with two calls to read_spec as:

rec = Record(file);
data = read_spec(rec, (Int32, 3));
line = read_spec(rec, (Int32, Int(rec.subleft/4)));
close(rec)

But I would like to decrease my calls to "read" if possible, as the Fortran implementation we have is about 5 times faster right now. Although I'm not sure if it can be solved in any other way, or exactly how Fortran handles this case internally.

**Comment by traktofon** [comment]
Sorry for the prolonged delay. I have cleaned up my macro code and added documentation and tests. This is now part of the current master (27cc03f). Note that support for julia-0.5 has been dropped. The package does work with julia-0.7 as is, though there are many deprecations (slowing things down).

Your example code
```fortran
READ(10) ICOL, IROW, NW, (WS(K), K=1, NW)
```
would translate into
```julia
@fread f icol::Int32 irow::Int32 nw::Int32 ws::Array{Float64}(nw)
```
where I have guessed the datatypes of your variables (adjust as needed), and `f` is the `FortranFile` corresponding to your Fortran unit 10.

I will tag a new release asap, so that updating to this version will be easy.

As for speed, this hasn't been a focus so far. The `read` function interface can cause a lot of compile overhead if there are many reads with different record signatures. The `@fread` macro interface expands to lengthier but potentially simpler code and thus might have less overhead.

**Comment by traktofon** [comment]
This is tagged as v0.4.0, awaiting merging into METADATA.

**Comment by mgcth** [comment]
Thank you! From a short test it seems the macro increased the read speed ~5 fold (close to Fortran implementation) compared to my home made solution (I must have done something very wrong). Luckily I haven't had to use the reader yet :).

**Comment by traktofon** [comment]
Thanks for testing, and happy to hear about the speed!
BTW the `@fread` macro also supports the shorter syntax for reading arrays, i.e.
```julia
@fread f icol::Int32 irow::Int32 nw::Int32 ws::(Float64,nw)
```
for your example. This is even more useful for julia-0.7, where one would need to add `undef` to the `Array` constructor.
